import { createClient } from '@sanity/client'
import * as dotenv from 'dotenv'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
dotenv.config({ path: join(__dirname, '../.env.local') })

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
  token: process.env.SANITY_API_WRITE_TOKEN,
  apiVersion: '2024-01-01',
  useCdn: false,
})

const docs = [
  {
    _id: 'siteSettings',
    _type: 'siteSettings',
    phone: '0879826292',
    phoneDisplay: '0879 826 292',
    email: 'office@newkey.bg',
    address: 'София, България',
    facebookUrl: 'https://facebook.com/newkeyproperties',
    instagramUrl: 'https://instagram.com/newkeyproperties',
    linkedinUrl: '',
    footerTagline: 'Доверие – Честност – Резултати',
    footerQuote: 'Работим с ограничен брой клиенти на месец, за да гарантираме най-високо качество на услугата.',
    footerCopyright: `© ${new Date().getFullYear()} New Key Properties. Всички права запазени.`,
    footerSubline: 'Лицензиран брокер на недвижими имоти в София, България.',
    formNameLabel: 'Вашето Име *',
    formNamePlaceholder: 'Иван Иванов',
    formPhoneLabel: 'Телефон *',
    formPhonePlaceholder: '0888 123 456',
    formEmailLabel: 'Имейл',
    formEmailPlaceholder: 'ivan@example.com',
    formMessageLabel: 'Съобщение *',
    formMessagePlaceholder: 'Търсите ли имот за покупка или наем? Разкажете ни повече...',
    formSubmitText: 'Изпратете Запитване',
    formLoadingText: 'Изпращане...',
    formSuccessTitle: 'Благодарим Ви!',
    formSuccessMessage: 'Получихме Вашето запитване. Ще се свържем с Вас в рамките на 24 часа.',
    formErrorMessage: 'Възникна грешка. Моля, опитайте отново или се обадете директно.',
    formFooterNote: 'Отговаряме в рамките на 24 часа. Местата са ограничени – свържете се с нас сега.',
  },
  {
    _id: 'homePage',
    _type: 'homePage',
    heroTitle: 'Намерете Имота',
    heroTitleGold: 'на Мечтите Си',
    heroSubtitle: 'Работим с ограничен брой клиенти на месец, за да гарантираме най-високо качество на услугата. Доверете се на екип, който работи като за себе си.',
    heroCtaButton: 'Разгледайте имотите',
    heroSecondaryButton: 'Безплатна консултация',
    statsClients: '150+',
    statsClientsLabel: 'Доволни клиенти',
    statsExperience: '10+',
    statsExperienceLabel: 'Години опит',
    statsRating: '5★',
    statsRatingLabel: 'Средна оценка',
    servicesTitle: 'Как Ви Помагаме',
    servicesSubtitle: 'Три основни услуги, с които покриваме всички Ви нужди при покупка, наем или инвестиция в имот.',
    service1Title: 'Покупка на Имот',
    service1Desc: 'Намираме точно това, което търсите — в рамките на Вашия бюджет и предпочитания.',
    service2Title: 'Наем на Имот',
    service2Desc: 'Бързо и безпроблемно намиране на наематели или жилище под наем.',
    service3Title: 'Инвестиционни Имоти',
    service3Desc: 'Консултации и анализи за максимална възвращаемост от инвестиции в имоти.',
    processTitle: 'Как Работим',
    processSubtitle: 'Прозрачен и лесен процес от първата среща до финалното договаряне.',
    processButtonText: 'Запазете консултация',
    processSteps: [
      { _key: 'step1', title: 'Среща и анализ', desc: 'Разговаряме с Вас, за да разберем точно какво търсите — без да губим времето Ви.' },
      { _key: 'step2', title: 'Подбор на имоти', desc: 'Представяме Ви само имоти, които отговарят на Вашите критерии.' },
      { _key: 'step3', title: 'Огледи и оценка', desc: 'Организираме огледи и даваме честна оценка за всеки имот.' },
      { _key: 'step4', title: 'Договаряне и сделка', desc: 'Водим преговорите от Ваше ime и гарантираме най-добрите условия.' },
    ],
    testimonialsTitle: 'Какво Казват Клиентите Ни',
    testimonialsSubtitle: 'Истински мнения от реални клиенти.',
    ctaTitle: 'Готови ли сте да намерите перфектния имот?',
    ctaSubtitle: 'Работим с ограничен брой клиенти — запазете своето място сега.',
    ctaButton: 'Безплатна консултация',
    ctaSecondaryButton: 'Разгледайте имотите',
  },
  {
    _id: 'aboutPage',
    _type: 'aboutPage',
    heroTitle: 'Честност и',
    heroTitleGold: 'Доверие',
    heroSubtitle: 'New Key Properties е агенция за недвижими имоти, която поставя клиента на първо място — винаги.',
    heroStory: 'Създадохме New Key Properties, защото вярваме, че пазарът на недвижими имоти се нуждае от повече честност и по-малко обещания. Работим с ограничен брой клиенти не защото не можем да поемем повече, а защото вярваме, че качеството е важно.',
    heroStats: [
      { _key: 'stat1', value: '150+', label: 'Доволни клиенти' },
      { _key: 'stat2', value: '10+', label: 'Години опит' },
      { _key: 'stat3', value: '5★', label: 'Средна оценка' },
    ],
    missionTitle: 'Нашата Мисия',
    missionText: 'Да бъдем най-честната агенция за недвижими имоти в София — такава, която работи изцяло в интерес на клиента.',
    valuesTitle: 'Нашите Ценности',
    value1Title: 'Честност',
    value1Desc: 'Казваме истината, дори когато тя не е удобна.',
    value2Title: 'Грижа',
    value2Desc: 'Третираме всяка сделка така, сякаш е наша собствена.',
    value3Title: 'Качество',
    value3Desc: 'Предпочитаме малко клиенти с отлично обслужване.',
    specializationTitle: 'С Какво Се Занимаваме',
    specializationSubtitle: 'Фокусирани сме в няколко ключови области на пазара на недвижими имоти в София.',
    specializations: [
      {
        _key: 'spec1',
        title: 'Жилищни имоти',
        items: ['Апартаменти под наем', 'Апартаменти за продажба', 'Къщи и вили', 'Ново строителство'],
      },
      {
        _key: 'spec2',
        title: 'Инвестиции',
        items: ['Инвестиционни апартаменти', 'Доходност и анализ', 'Управление на имоти', 'Портфолио консултации'],
      },
    ],
    ctaTitle: 'Работете с Честни Брокери',
    ctaSubtitle: 'Свържете се с нас и вижте разликата.',
    ctaButton: 'Свържете се с нас',
  },
  {
    _id: 'contactPage',
    _type: 'contactPage',
    heroTitle: 'Свържете се',
    heroTitleGold: 'с Нас',
    heroSubtitle: 'Работим с ограничен брой клиенти на месец. Свържете се с нас сега и запазете своето място.',
    contactInfoLabel: 'Връзка с нас',
    contactInfoTitle: 'Информация за контакт',
    phone: '0879826292',
    phoneHours: 'Пон – Пет: 09:00 – 18:00, Сб: 10:00 – 15:00',
    email: 'office@newkey.bg',
    emailNote: 'Отговаряме в рамките на 24 часа',
    address: 'София, България',
    addressNote: 'Обслужваме целия град',
    urgencyTitle: 'Ограничени места',
    urgencyMessage: 'Работим с максимум 10 клиента на месец, за да гарантираме най-високо качество.',
    formTitle: 'Изпратете запитване',
    formSubtitle: 'Попълнете формата и ще се свържем с Вас в рамките на 24 часа.',
  },
  {
    _id: 'consultationPage',
    _type: 'consultationPage',
    heroTitle: 'Безплатна',
    heroTitleGold: 'Консултация',
    heroSubtitle: 'Запишете се за безплатна консултация с наш брокер. Без задължения, без скрити такси.',
    heroBookButton: 'Запишете се сега',
    heroCallButton: 'Обадете се',
    benefitsTitle: 'Какво Включва Консултацията',
    benefit1Title: 'Анализ на нуждите',
    benefit1Desc: 'Разбираме точно какво търсите.',
    benefit2Title: 'Пазарен анализ',
    benefit2Desc: 'Актуални цени и тенденции в района.',
    benefit3Title: 'Без задължения',
    benefit3Desc: 'Консултацията е напълно безплатна.',
    formSectionTitle: 'Запишете се за Консултация',
    formSectionSubtitle: 'Попълнете формата и ще се свържем с Вас в рамките на 24 часа.',
    formCardBadge: 'Безплатна консултация',
    formCardTitle: 'Запазете своето място',
    formCardSubtitle: 'Местата за този месец са ограничени.',
    faqTitle: 'Често Задавани Въпроси',
    bottomCtaTitle: 'Готови ли сте да направите следващата стъпка?',
    bottomCtaSubtitle: 'Свържете се с нас сега и намерете правилния имот.',
    bottomCtaButton1: 'Запишете се за консултация',
    bottomCtaButton2: 'Разгледайте имотите',
  },
  {
    _id: 'blogPage',
    _type: 'blogPage',
    heroTitle: 'Нашият',
    heroTitleGold: 'Блог',
    heroSubtitle: 'Полезни статии, съвети и актуална информация за пазара на недвижими имоти в София.',
    ctaTitle: 'Имате въпроси за пазара?',
    ctaSubtitle: 'Свържете се с нас за безплатна консултация.',
  },
  {
    _id: 'teamPage',
    _type: 'teamPage',
    heroTitle: 'Хора, на Които',
    heroTitleGold: 'Можете да Разчитате',
    heroSubtitle: 'Нашият екип е малък, но всеотдаен. Всеки от нас подхожда към работата с максимална грижа и честност.',
    teamGridLabel: 'Нашите хора',
    teamGridTitle: 'Запознайте се с нас',
    philosophyTitle: 'Нашата Философия',
    philosophyItems: [
      { _key: 'phi1', title: 'Качество над количество', text: 'Работим с ограничен брой клиенти на месец — не защото не искаме повече работа, а защото вярваме, че качеството е по-важно от количеството. Всеки клиент заслужава пълното ни внимание.' },
      { _key: 'phi2', title: 'Работим като за себе си', text: 'Когато работим с Вас, третираме Вашия имот и Вашите интереси така, сякаш са наши. Това не е маркетинг — това е начинът, по който сме решили да работим.' },
    ],
    ctaTitle: 'Свържете се с нашия екип',
    ctaSubtitle: 'Готови сме да отговорим на Вашите въпроси и да Ви помогнем с намирането на правилния имот.',
  },
  {
    _id: 'listingsPage',
    _type: 'listingsPage',
    heroTitle: 'Намерете',
    heroTitleGold: 'Вашия Имот',
    heroSubtitle: 'Разгледайте нашите актуални обяви — апартаменти и къщи за наем и продажба в София.',
    bottomCtaTitle: 'Не намерихте подходящ имот?',
    bottomCtaSubtitle: 'Свържете се с нас и ще намерим точно това, което търсите.',
  },
]

async function seed() {
  console.log('Seeding Sanity documents...\n')
  for (const doc of docs) {
    try {
      await client.createOrReplace(doc)
      console.log('✓ ' + doc._id)
    } catch (err) {
      console.error('✗ ' + doc._id + ':', err.message)
    }
  }
  console.log('\nDone!')
}

seed()
